---
abstract: unknown
author:
  - 'Ivan Baktsheev <dot.and.thing@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Time::HiRes: 0
  perl: 5.008006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Easy
  homepage: http://perlhug.com
  license: http://dev.perl.org/licenses/
  repository: git://web-app.git.sourceforge.net/gitroot/perl-easy/perl-easy
version: 0.18
